name: Test WF

on:
  push:
  pull_request:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - run: echo "1"
    - run: |
        touch test1
        touch test2
    - uses: actions/upload-artifact@v2
      with:
        name: sycl_linux_default
        path: test1
    - uses: actions/upload-artifact@v2
      with:
        name: sycl_linux_test
        path: test2
