name: Test WF

on:
  push:
  pull_request:

jobs:
  lint:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
    - run: echo "lint"
  build:
    needs: ${{ github.event.name == 'pull_request' ? [lint] : []}}
    runs-on: ubuntu-latest
    if: ${{ github.event.name == 'push' || needs.lint.result == 'success' }}
    steps:
    - run: echo "build"
