name: Test WF

on:
  push:
  pull_request:

jobs:
  resolve_matrix:
    runs-on: ubuntu-latest
    outputs:
      lts: ${{ steps.work.outputs.lts }}
    steps:
    - run: |
        wget raw.githubusercontent.com/alexbatashev/actions_playground/${{ github.sha }}/devops/test_configs.json
        wget raw.githubusercontent.com/alexbatashev/actions_playground/${{ github.sha }}/devops/scripts/generate_test_matrix.js
    - uses: actions/github-script@v6
      env:
        GHA_INPUT: ${{ toJSON(inputs) }}
      with:
        script: |
          const script = require('./generate_test_matrix.js');
          script({core, process});

  test:
    name: Run Tests
    needs: [resolve_matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ needs.resolve_matrix.outputs.lts }}
    steps:
    - run: echo "1"
